# global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'external'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'

# alertmanager
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
         - targets: ['localhost:9090']
  # - job_name: 'node-exporter'
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  
  # - job_name: 'custom-exporter'
  #   scrape_interval: 15s

  #   static_configs:
  #     - targets: ['google.com']
